package com.example.catalog.model


import org.springframework.data.redis.core.RedisHash

//TODO add autogenerated id
interface Entity {
    val id: String
}

@RedisHash("Product")
data class Product(override val id: String, val name: String, val price: Double, val description: String) : Entity